included:
  - Sources
  - Tests
  - Examples

excluded:
  - .build
  - Pods
  - DerivedData

disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - sorted_imports

line_length:
  warning: 140
  error: 180
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 80
  error: 120

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - x
    - y

reporter: xcode
