platform :osx, '12.0'
use_frameworks!
project 'MMMDKitMacDemo.xcodeproj'

target 'MMMDKitMacDemo' do
  pod 'MMMDCore', :path => '../..'
  pod 'MMMDParserCmark', :path => '../..'
  pod 'MMMDStreaming', :path => '../..'
  pod 'MMMDHighlighter', :path => '../..'
  pod 'MMMDMath', :path => '../..'
  pod 'MMMDHTML', :path => '../..'
  pod 'MMMDAppKit', :path => '../..'
end
